package it.unipd.math.plg.ui.utils;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 * A very basic class for keeping track of the logs generated by the application
 * 
 * @author Andrea Burattin
 */
public class PLGLogger {
	
	private boolean firstLog = true;
	private JTextArea logOutput;
	private JScrollPane logOutputContainer;
	
	private static PLGLogger instance = new PLGLogger();
	
	
	public static PLGLogger instance() {
		return instance;
	}
	
	
	public void setLogOutput(JTextArea logOutput, JScrollPane logOutputContainer) {
		this.logOutput = logOutput;
		this.logOutputContainer = logOutputContainer;
	}
	
	
	public static void log(String message) {
		StackTraceElement callerElement = new Throwable().getStackTrace()[1];
		String caller = callerElement.getClassName() + "::" + callerElement.getMethodName() + " (" + callerElement.getFileName() + ":" + callerElement.getLineNumber() + ")";
		
		if (instance().firstLog) {
			instance().firstLog = false;
		} else {
			instance().logOutput.append("\n");
		}
		instance().logOutput.append(DateUtils.now() + " - " + caller + " - " + message);
		instance().logOutput.setCaretPosition(instance.logOutput.getText().length());
	}
}
