/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PLGComparison.java
 *
 * Created on May 4, 2011, 7:17:48 PM
 */
package it.unipd.math.plg.ui;

import it.processmining.metric.metric.JaccardDistance;
import it.unipd.math.plg.models.PlgProcess;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JInternalFrame;
import org.processmining.framework.models.heuristics.HeuristicsNet;

/**
 *
 * @author delas
 */
public class PLGComparison extends javax.swing.JInternalFrame {
	
	PLGMainUI mainUI = null;

    /** Creates new form PLGComparison */
    public PLGComparison(PLGMainUI mainUI) {
		this.mainUI = mainUI;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.unipd.math.plg.ui.ProcessLogGeneratorApp.class).getContext().getResourceMap(PLGComparison.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(resourceMap.getFont("jTextArea1.font")); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		
		Vector<HeuristicsNet> processes = new Vector<HeuristicsNet>();
		
		jTextArea1.setText("");
		jTextArea1.append("Process list\n");
		jTextArea1.append("============\n");
		
		int i = 0;
		for(JInternalFrame jif : mainUI.getAllWindow()) {
			if (jif instanceof PLGProcessWindow) {
				PLGProcessWindow p = (PLGProcessWindow)jif;
				processes.add(p.getProcess().getHeuristicsNet());
				jTextArea1.append(i++ + ". " + p.getTitle() + "\n");
			}
		}
		
		jTextArea1.append("\n");
		jTextArea1.append("Processes similarities\n");
		jTextArea1.append("======================\n");
		
		// title
		jTextArea1.append("\t");
		i = 0;
		for(HeuristicsNet hn : processes) {
			jTextArea1.append(i++ + "\t");
		}
		jTextArea1.append("\n");
		
		// table content
		for(i = 0; i < processes.size(); i++) {
			for(int j = 0; j < processes.size(); j++) {
				if (j==0) {
					jTextArea1.append(i + "\t");
				}
				Double m = 1-JaccardDistance.getDistance(processes.elementAt(i), processes.elementAt(j));
				DecimalFormat twoDForm = new DecimalFormat("#.#####");
				jTextArea1.append(Double.valueOf(twoDForm.format(m)) +"\t");
				
				if (j==i) {
					break;
				}
			}
			jTextArea1.append("\n");
		}
		jTextArea1.append("\n");
		
	}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
