/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PLGExploreHierarchy.java
 *
 * Created on Jul 1, 2011, 7:55:55 PM
 */
package it.unipd.math.plg.ui;

import it.processmining.clustering.exceptions.ClusteringException;
import it.processmining.clustering.hierarchical.Cluster;
import it.processmining.clustering.hierarchical.HierarchicalClustering;
import it.processmining.clustering.model.process.HeuristicsNetSetRepresentation;
import it.unipd.math.plg.models.PlgProcess;
import it.unipd.math.plg.ui.utils.PLGLogger;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JSplitPane;

/**
 *
 * @author delas
 */
public class PLGExploreHierarchy extends javax.swing.JInternalFrame {

	private PLGMainUI mainUI = null;
	private HashSet<HeuristicsNetSetRepresentation> elements = null;
	private Cluster root = null;
	
	
	/** Creates new form PLGExploreHierarchy */
	public PLGExploreHierarchy(PLGMainUI mainUI) {
		
		this.mainUI = mainUI;
		
		initComponents();
		getProcesses();
		clusterize();
		
		updateClusterView(root);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.unipd.math.plg.ui.ProcessLogGeneratorApp.class).getContext().getResourceMap(PLGExploreHierarchy.class);
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel1, gridBagConstraints);

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jButton1, gridBagConstraints);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel2, gridBagConstraints);

        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jButton2, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel4, gridBagConstraints);

        jPanel3.add(jPanel1);

        jSplitPane1.setRightComponent(jPanel3);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables


	private void getProcesses() {
		
		if (elements == null) {
			elements = new HashSet<HeuristicsNetSetRepresentation>();
		} else {
			elements.clear();
		}
		
		for (JInternalFrame jif : mainUI.getAllWindow()) {
			if (jif instanceof PLGProcessWindow) {
				PLGProcessWindow p = (PLGProcessWindow)jif;
				PlgProcess proc = p.getProcess();
				HeuristicsNetSetRepresentation hnsr = new HeuristicsNetSetRepresentation(p.getTitle(), proc.getHeuristicsNet());
				hnsr.setProcessRepresentative(proc);
				elements.add(hnsr);
			}
		}
	}
	
	
	private void clusterize() {
		try {
			PLGLogger.log("Starting clustering");
			root = HierarchicalClustering.cluster(elements, 1.0);
			PLGLogger.log("Clustering done");
		} catch (ClusteringException ex) {
			PLGLogger.log("ERROR: " + ex.getMessage());
			Logger.getLogger(PLGExploreHierarchy.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	
	private void updateClusterView(Cluster root) {
		if (root != null) {
			Cluster[] children = root.getChildren();
			if (children[0] != null && children[1] != null) {
				PlgProcess pLeft = (PlgProcess) children[0].getMedoid().getProcessRepresentative();
				PlgProcess pRight = (PlgProcess) children[1].getMedoid().getProcessRepresentative();
				
				// left child
				JComponent cLeft = pLeft.getHeuristicsNet().getGrappaVisualization();
				((JSplitPane)cLeft.getComponent(0)).getRightComponent().setMinimumSize(new Dimension());
				((JSplitPane)cLeft.getComponent(0)).setDividerLocation(1.0d);
				jPanel4.removeAll();
				jPanel4.add(cLeft, BorderLayout.CENTER);
				jLabel1.setText(pLeft.getName());
				jLabel3.setText("Cluster size: " + children[0].getAllElements().size());
				
				// right child
				JComponent cRight = pRight.getHeuristicsNet().getGrappaVisualization();
//				((JSplitPane)cRight.getComponent(0)).getRightComponent().setMinimumSize(new Dimension());
//				((JSplitPane)cRight.getComponent(0)).setDividerLocation(1.0d);
				jPanel2.removeAll();
//				jPanel2.add(cRight, BorderLayout.CENTER);
				jLabel2.setText(pRight.getName());
//				jLabel4
			}
		}
	}

}
